---
- name: Set up NAS
  hosts: raspberries

  tasks:
    - name: Load secret vars
      community.sops.load_vars:
        file: vars.enc.yml

    - name: Install samba
      ansible.builtin.apt:
        update_cache: true
        name:
          - samba
          - samba-common-bin
      become: true

    - name: Add group
      ansible.builtin.group:
        name: "{{ nas_user }}"
        state: present
      become: true

    - name: Add user
      ansible.builtin.user:
        name: "{{ nas_user }}"
        groups: "{{ nas_user }}"
        shell: /sbin/nologin
        create_home: false
      become: true

    - name: Mount harddrive
      ansible.posix.mount:
        path: "{{ mountpoint }}"
        src: "{{ device }}"
        state: mounted
        fstype: ext4
        opts: defaults,noatime
      become: true

    - name: Create shared folder
      ansible.builtin.file:
        name: "{{ shared_dir }}"
        state: directory
        mode: "777"
        owner: "{{ nas_user }}"
        group: "{{ nas_user }}"
        recurse: true
      become: true

    - name: Copy config template
      become: true
      ansible.builtin.template:
        src: files/smb.j2.conf
        dest: /etc/samba/smb.conf
        mode: "644"
        validate: testparm -s %s
      notify:
        - Restart smbd
        - Restart nmbd

    - name: Set smb password
      ansible.builtin.shell: >
        set -e -o pipefail
        && (echo '{{ nas_password }}'; echo '{{ nas_password }}') | smbpasswd -s -a {{ nas_user }}
      register: output
      changed_when: "'Added user' in output.stdout"
      become: true

  handlers:
    - name: Restart smbd
      ansible.builtin.systemd:
        name: smbd
        state: restarted
      become: true

    - name: Restart nmbd
      ansible.builtin.systemd:
        name: nmbd
        state: restarted
      become: true
